AWSTemplateFormatVersion: 2010-09-09
Description: "CF template to deploy Peaches&Plums VPC, with 4 subnets across 2 AZs"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.90.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P
#  IPv6CidrBlock:
#    Type: AWS::EC2::VPCCidrBlock
#    Properties:
#      VpcId: !Ref VPC
#      AmazonProvidedIpv6CidrBlock: true
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P
        - Key: function
          Value: webtraffic
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW
  routeTableWeb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P
        - Key: function
          Value: webtraffic
  routeTableDefaultIPv4:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId:
        Ref: routeTableWeb
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        Ref: IGW
#  routeTableDefaultIPv6:
#    Type: AWS::EC2::Route
#    DependsOn: IGWAttachment
#    Properties:
#      RouteTableId:
#        Ref: routeTableWeb
#      DestinationIpv6CidrBlock: '::/0'
#      GatewayId:
#        Ref: IGW
  routeTableAssociationPubA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPubA
      RouteTableId:
        Ref: routeTableWeb
  routeTableAssociationPubB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPubB
      RouteTableId:
        Ref: routeTableWeb
  SubnetPubA:
    Type: AWS::EC2::Subnet
#    DependsOn: IPv6CidrBlock
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.10.0/24
#      Ipv6CidrBlock: 
#        Fn::Sub:
#          - "${VpcPart}${SubnetPart}"
#          - SubnetPart: '00::/64'
#            VpcPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P
  SubnetPrivA:
    Type: AWS::EC2::Subnet
#    DependsOn: IPv6CidrBlock
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.100.0/24
#     Ipv6CidrBlock: 
#        Fn::Sub:
#          - "${VpcPart}${SubnetPart}"
#          - SubnetPart: '00::/64'
#            VpcPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P
  SubnetPubB:
    Type: AWS::EC2::Subnet
#    DependsOn: IPv6CidrBlock
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.12.0/24
#      Ipv6CidrBlock: 
#        Fn::Sub:
#          - "${VpcPart}${SubnetPart}"
#          - SubnetPart: '00::/64'
#            VpcPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P
  SubnetPrivB:
    Type: AWS::EC2::Subnet
#    DependsOn: IPv6CidrBlock
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.102.0/24
#      Ipv6CidrBlock: 
#        Fn::Sub:
#          - "${VpcPart}${SubnetPart}"
#          - SubnetPart: '00::/64'
#            VpcPart: !Select [ 0, !Split [ '00::/56', !Select [ 0, !GetAtt VPC.Ipv6CidrBlocks ]]]
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: P&P

Outputs:
  pnpvpc1:
    Description: Peaches and Plums VPC_ID
    Value: !Ref VPC
    Export: 
      Name: pnp-vpc1
  pnpvpc1subnetpuba:
    Description: Peaches and Plums SubnetPubA
    Value: !Ref SubnetPubA
    Export: 
      Name: pnp-vpc1-subnet-pub-a
  pnpvpc1subnetpriva:
    Description: Peaches and Plums SubnetPrivA
    Value: !Ref SubnetPrivA
    Export: 
      Name: pnp-vpc1-subnet-priv-a
  pnpvpc1subnetpubb:
    Description: Peaches and Plums SubnetPubB
    Value: !Ref SubnetPubB
    Export: 
      Name: pnp-vpc1-subnet-pub-b
  pnpvpc1subnetprivb:
    Description: Peaches and Plums SubnetPrivB
    Value: !Ref SubnetPrivB
    Export: 
      Name: pnp-vpc1-subnet-priv-b