AWSTemplateFormatVersion: 2010-09-09
Description: "CF template to deploy Peaches&Plums VPC, with 4 subnets across 2 AZs"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.90.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
        - Key: function
          Value: webtraffic
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW
  routeTableWeb:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
        - Key: function
          Value: webtraffic
  routeTableDefaultIPv4:
    Type: AWS::EC2::Route
    DependsOn: IGWAttachment
    Properties:
      RouteTableId:
        Ref: routeTableWeb
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        Ref: IGW
  routeTableAssociationPubA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPubA
      RouteTableId:
        Ref: routeTableWeb
  routeTableAssociationPubB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPubB
      RouteTableId:
        Ref: routeTableWeb
  routeTableAssociationPubC:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetPubC
      RouteTableId:
        Ref: routeTableWeb
  SubnetPubA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.10.0/24
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
  SubnetPrivA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.110.0/24
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
  SubnetPubB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.12.0/24
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
  SubnetPrivB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.112.0/24
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
  SubnetPubC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.14.0/24
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp
  SubnetPrivC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      VpcId: !Ref VPC
      CidrBlock: 10.90.114.0/24
      Tags:
        - Key: environment
          Value: dev
        - Key: application
          Value: pandp

Outputs:
  pandpvpc1:
    Description: Peaches and Plums VPC_ID
    Value: !Ref VPC
    Export: 
      Name: pandp-vpc1
  pandpvpc1subnetpuba:
    Description: Peaches and Plums SubnetPubA
    Value: !Ref SubnetPubA
    Export: 
      Name: pandp-vpc1-subnet-pub-a
  pandpvpc1subnetpriva:
    Description: Peaches and Plums SubnetPrivA
    Value: !Ref SubnetPrivA
    Export: 
      Name: pandp-vpc1-subnet-priv-a
  pandpvpc1subnetpubb:
    Description: Peaches and Plums SubnetPubB
    Value: !Ref SubnetPubB
    Export: 
      Name: pandp-vpc1-subnet-pub-b
  pandpvpc1subnetprivb:
    Description: Peaches and Plums SubnetPrivB
    Value: !Ref SubnetPrivB
    Export: 
      Name: pandp-vpc1-subnet-priv-b
  pandpvpc1subnetpubc:
    Description: Peaches and Plums SubnetPubC
    Value: !Ref SubnetPubC
    Export: 
      Name: pandp-vpc1-subnet-pub-c
  pandpvpc1subnetprivc:
    Description: Peaches and Plums SubnetPrivC
    Value: !Ref SubnetPrivC
    Export: 
      Name: pandp-vpc1-subnet-priv-c